### ISSUE TITLE
TypeError: type of argument schedule must be one of (aws_cdk.aws_events.Schedule, NoneType); got aws_cdk._ScheduleProxy instead

### ISSUE THREAD

**Issue by fucksmile** [awslabs/aws-media-replay-engine#21]
Hello team,

Traceback (most recent call last):
  File "/home/ubuntu/aws-media-replay-engine/source/backend/event-life-cycle/infrastructure/app.py", line 6, in <module>
    ChaliceApp(app, 'aws-mre-event-life-cycle')
  File "/tmp/tmp.PoDCm46Eak/lib/python3.10/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/home/ubuntu/aws-media-replay-engine/source/backend/event-life-cycle/infrastructure/stacks/chaliceapp.py", line 245, in __init__
    self.schedule_cleanup_cron_rule = events.Rule(self, "ScheduleCleanupCronRule",
  File "/tmp/tmp.PoDCm46Eak/lib/python3.10/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/tmp/tmp.PoDCm46Eak/lib/python3.10/site-packages/aws_cdk/aws_events/__init__.py", line 9547, in __init__
    props = RuleProps(
  File "/tmp/tmp.PoDCm46Eak/lib/python3.10/site-packages/aws_cdk/aws_events/__init__.py", line 9757, in __init__
    check_type(argname="argument schedule", value=schedule, expected_type=type_hints["schedule"])
  File "/tmp/tmp.PoDCm46Eak/lib/python3.10/site-packages/typeguard/__init__.py", line 757, in check_type
    checker_func(argname, value, expected_type, memo)
  File "/tmp/tmp.PoDCm46Eak/lib/python3.10/site-packages/typeguard/__init__.py", line 558, in check_union
    raise TypeError('type of {} must be one of ({}); got {} instead'.
TypeError: type of argument schedule must be one of (aws_cdk.aws_events.Schedule, NoneType); got aws_cdk._ScheduleProxy instead

Subprocess exited with error 1
ERROR: Failed to deploy the Event Life Cycle Handler stack.

**Comment by fucksmile** [comment]
aws-cdk bug in 2.97.0
