### ISSUE TITLE
Error: The stack named aws-mre-segment-caching failed creation .... AWS::Lambda::Function   | MreSegmentCaching4BB22A99 Resource handler returned message: "'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008

### ISSUE THREAD

**Issue by gvasquez95** [awslabs/aws-media-replay-engine#4]
Seems like there might be an issue with memory config of a lambda function within the stack. I tried to deploy it and came across this unfortunate error message:

```
aws-mre-segment-caching: creating CloudFormation changeset...
6:44:47 PM | CREATE_FAILED        | AWS::Lambda::Function   | MreSegmentCaching4BB22A99
Resource handler returned message: "'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008 (Service: Lambda, Status Code: 400, Request ID: 88
f3658e-8ea8-4bfa-a42b-c86deed00c86)" (RequestToken: ef8c4686-e025-7dc2-dcb6-44bc1a6c2a73, HandlerErrorCode: InvalidRequest)

 ❌  aws-mre-segment-caching failed: Error: The stack named aws-mre-segment-caching failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008 (Service: Lambda, Status Code: 400, Request ID: 88f3658e-8ea8-4bfa-a42b-c86deed00c86)" (RequestToken: ef8c4686-e025-7dc2-dcb6-44bc1a6c2a73, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:505:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at deployStack2 (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:265:24)
    at /usr/local/lib/node_modules/aws-cdk/lib/deploy.ts:39:11
    at run (/usr/local/lib/node_modules/p-queue/dist/index.js:163:29)

 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named aws-mre-segment-caching failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008 (Service: Lambda, Status Code: 400, Request ID: 88f3658e-8ea8-4bfa-a42b-c86deed00c86)" (RequestToken: ef8c4686-e025-7dc2-dcb6-44bc1a6c2a73, HandlerErrorCode: InvalidRequest)
    at deployStacks (/usr/local/lib/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:339:7)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/lib/cli.ts:374:12)

Stack Deployments Failed: Error: The stack named aws-mre-segment-caching failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008 (Service: Lambda, Status Code: 400, Request ID: 88f3658e-8ea8-4bfa-a42b-c86deed00c86)" (RequestToken: ef8c4686-e025-7dc2-dcb6-44bc1a6c2a73, HandlerErrorCode: InvalidRequest)
ERROR: Failed to deploy the Segment Caching stack.
```

Deployed using:

`./build-and-deploy.sh --enable-ssm-high-throughput --version $VERSION --region $REGION`

VERSION=2.5.1 and REGION=us-east-1

What else could I provide to assist debugging?

**Comment by araviraj-aws** [comment]
Hi @gvasquez95 ! Thanks for sharing the error message along with the deployment command. Given you're trying to deploy MRE in the us-east-1 region, Lambda should technically support up to 10,240 megabytes for the MemorySize config. However, there was a recent introduction of a limitation in Lambda **for new accounts** where they have reduced concurrency and memory quotas (https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html). To confirm this, can you navigate to this link (after logging into the AWS Console) - https://us-east-1.console.aws.amazon.com/servicequotas/home/services/lambda/quotas/L-C351E702 and see if you're able to request a quota increase for 10,240 megabytes? Thanks!

**Comment by marcos-acosta** [comment]
I had the same issue, contacting support was able to resolve it.

**Comment by navarrodiego** [comment]
I have the same issue. When I click the link to see the maximum memory size for my lambdas, it is 10,240 MB. But I still get the error.

**Comment by aravindkaws** [comment]
Hi @gvasquez95 
I would recommend that you reach out to AWS Support to help troubleshoot this problem.
